"""'leveling'

Revision ID: a2595506bda5
Revises: 9dd273ef61a0
Create Date: 2024-12-22 16:47:26.537380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2595506bda5'
down_revision: Union[str, None] = '9dd273ef61a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('text', sa.String(), nullable=True))
    op.add_column('subscription_plans', sa.Column('level', sa.Integer(), nullable=True, default=1, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'level')
    op.drop_column('subscription_plans', 'text')
    # ### end Alembic commands ###
