"""'scripts_subscriptions'

Revision ID: dd605031fdb4
Revises: a2595506bda5
Create Date: 2025-02-03 16:41:21.194512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd605031fdb4'
down_revision: Union[str, None] = 'a2595506bda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.DATE(), nullable=True),
    sa.Column('end_time', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['owner_telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripts_subscriptions')
    # ### end Alembic commands ###
